---
# PiCamera options.
picamera:
    # Where to store taken pictures.
    photo_directory: "/home/pi/pimaton_pictures"
    # Format of the taken picture, png or jpg.
    picture_format: 'png'
    number_of_pictures_to_take: 6
    time_before_first_picture: 4
    time_between_pictures: 2
    # Prefix for the name of the taken pictures.
    picture_prefix_name: "test_pimaton"
    # PiCamera specific settings.
    # For more information, see the PiCamera class here:
    # https://picamera.readthedocs.io/en/latest/api_camera.html
    settings:
        resolution:
            width: 560
            height: 496
        framerate: 30
        sharpness: 0
        contrast: 0
        brightness: 50
        saturation: 0
        iso: 0
        video_stabilization: False
        exposure_compensation: 0
        exposure_mode: 'auto'
        meter_mode: 'backlit'
        awb_mode: 'auto'
        rotation: 0
        hflip: True
        vflip: False
        annotate_text_size: 80

# Pimaton global options.
pimaton:
    time_between_loop: 2
    # UI mode, can be tui (Text user interface) or GUI (graphical user interface)
    # For the GUI to work, you need X and a desktop manager.
    # Only tui mode is available for now.
    ui_mode: 'tui'
    inputs:
        - "keyboard" # React on "enter" key.
        # - GPIO # Not available yet. See full example file.

# Image options.
image:
    print_pic:
        # Format of the generated image, png or jpg.
        image_format: 'png'
        # Prefix for the generated image.
        generated_prefix_name: "pimaton"
        # Path for the template jpg to use if any. 
        # Put empty string if no template.
        template: None
        # Directory where are stored the generated pictures.
        output_dir: "/home/pi/pimaton_pictures"
        # Width and Height of the generated image.
        width: 1241
        height: 1754
        # Columns and Rows for the generated image.
        rows: 3
        cols: 2
        # If a QR code direct to the session gallery should be printed.
        qr_code_enabled: false

    # Thumbnails size.
    thumbnails:
        width: 560
        height: 496

print:
    # If pimaton should try to print the generated picture.
    enabled: false

# Synchronisation options.
sync:
    # IF you want to enable synchronisation to a remote server.
    enabled: false
